language: node_js
node_js:
  - "10"

cache:
  yarn: true
  directories:
    - server/node_modules
    - client/node_modules

jobs:
  include:
    - stage: dependencies
      script: cd server && yarn
      script: cd client && yarn
    - stage: test
      script: cd server && yarn test
      script: cd client && yarn test
    - stage: build
      script: cd server && yarn build
      script: cd client && yarn build